image: node:12

stages:
  - install
  - build
  - quality
  - test
  - deploy

cache:
  paths:
    - .npm

install:
  stage: install
  script:
    - npm ci
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - .npm/
      - node_modules

build:
  stage: build
  script:
    - CI=false npm run build
  artifacts:
    paths:
      - build
    expire_in: 30 mins
  dependencies:
    - install

# Consider adding linting rules and a linting check to your pipeline
# linting:
#   stage: quality
#   script:
#     - npm run lint

test_unit:
   stage: quality
   script:
      -  CI=true npm run test:unit
   dependencies:
      - install
   coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

staging:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=[YOUR_HEROKU_APP_NAME] --api-key=$HEROKU_API_KEY
  only:
    - master
  dependencies:
    - build
